//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by NguyenNgocChau@VFA
//

import Foundation

//MARK: Router -
protocol ___VARIABLE_productName:identifier___WireframeProtocol: class {

}
//MARK: Presenter -
protocol ___VARIABLE_productName:identifier___PresenterProtocol: class {

}

//MARK: View -
protocol ___VARIABLE_productName:identifier___ViewProtocol: class {

   var presenter: ___VARIABLE_productName:identifier___PresenterProtocol?  { get set }
}
