//
//  CircleProtocols.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/18/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by NguyenNgocChau@VFA
//

import Foundation

//MARK: Router -
protocol CircleWireframeProtocol: class {

}
//MARK: Presenter -
protocol CirclePresenterProtocol: class {

}

//MARK: View -
protocol CircleViewProtocol: class {

  var presenter: CirclePresenterProtocol?  { get set }
}
