//
//  CircleRouter.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/18/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by NguyenNgocChau@VFA
//

import UIKit

class CircleRouter: CircleWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = CircleViewController(nibName: nil, bundle: nil)
        let router = CircleRouter()
        let presenter = CirclePresenter(interface: view, router: router)
        
        view.presenter = presenter
        router.viewController = view
        return view
    }
}
