//
//  RegisterViewController.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/17/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RegisterViewController: UIViewController, RegisterViewProtocol {

	var presenter: RegisterPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
