//
//  SearchCityViewController.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/18/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by NguyenNgocChau@VFA
//

import UIKit

class SearchCityViewController: UIViewController, SearchCityViewProtocol {

    @IBOutlet weak var searchBar: UISearchBar!
    var presenter: SearchCityPresenterProtocol?
    @IBOutlet weak var tbvView: UITableView!
    var identifier = "SearchCityCell"
    
    var shownCities = [String]()
    let allCities = ["New York", "London", "Oslo", "Warsaw", "Berlin", "Praga"]
//    var disposeBag = DisposeBag()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        tbvView.dataSource = self
        tbvView.register(UINib(nibName: identifier, bundle: nil), forCellReuseIdentifier: identifier)
//        self.searchBar.rx.text.throttle(RxTimeInterval.seconds(10), scheduler: MainScheduler.instance)
//        .distinctUntilChanged()
//        .subscribe(onNext: {element in
//            self.shownCities = self.allCities.filter{ $0.contains(element ?? "") }
//            self.tbvView.reloadData()
//        }).disposed(by: disposeBag)
    }
}

extension SearchCityViewController: UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return shownCities.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let cell = tableView.dequeueReusableCell(withIdentifier: identifier, for: indexPath) as? SearchCityCell {
            cell.titleLabel.text = shownCities[indexPath.row]
            return cell
        }
        return UITableViewCell()
    }
}
