//
//  SearchCityPresenter.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/18/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by NguyenNgocChau@VFA
//

import UIKit

class SearchCityPresenter: SearchCityPresenterProtocol {

    weak private var view: SearchCityViewProtocol?
    private let router: SearchCityWireframeProtocol

    init(interface: SearchCityViewProtocol, router: SearchCityWireframeProtocol) {
        self.view = interface
        self.router = router
    }

}
