//
//  SearchCityProtocols.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/18/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by NguyenNgocChau@VFA
//

import Foundation

//MARK: Router -
protocol SearchCityWireframeProtocol: class {

}
//MARK: Presenter -
protocol SearchCityPresenterProtocol: class {

}

//MARK: View -
protocol SearchCityViewProtocol: class {

  var presenter: SearchCityPresenterProtocol?  { get set }
}
