//
//  SearchCityRouter.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/18/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by NguyenNgocChau@VFA
//

import UIKit

class SearchCityRouter: SearchCityWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SearchCityViewController(nibName: nil, bundle: nil)
        let router = SearchCityRouter()
        let presenter = SearchCityPresenter(interface: view, router: router)
        
        view.presenter = presenter
        router.viewController = view
        return view
    }
}
