//
//  LoginProtocols.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/19/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by NguyenNgocChau@VFA
//

import Foundation

//MARK: Router -
protocol LoginWireframeProtocol: class {
    func gotoBook()
}
//MARK: Presenter -
protocol LoginPresenterProtocol: class {
    func checkValidate(email: String, password: String)
    func gotoBook()
}

//MARK: View -
protocol LoginViewProtocol: class {
    func didCheckValidate(error: String)
    func didCheckValidate()
    var presenter: LoginPresenterProtocol?  { get set }
}
