//
//  LoginViewController.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/19/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by NguyenNgocChau@VFA
//

import UIKit

class LoginViewController: UIViewController {

    @IBOutlet weak var lblError: UILabel!
    @IBAction func login(_ sender: Any) {
        let email = tfEmail.text ?? ""
        let password = tfPassword.text ?? ""
        self.presenter?.checkValidate(email: email, password: password)
    }
    
    @IBOutlet weak var tfPassword: UITextField!
    @IBOutlet weak var tfEmail: UITextField!
    
    var presenter: LoginPresenterProtocol?

    override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationItem.title = "Login"
    }

}

extension LoginViewController : LoginViewProtocol {
    func didCheckValidate(error: String) {
        lblError.text = error
    }
    
    func didCheckValidate() {
        lblError.text = ""
        self.presenter?.gotoBook()
    }
}
