//
//  BookProtocols.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/19/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by NguyenNgocChau@VFA
//

import Foundation

//MARK: Router -
protocol BookWireframeProtocol: class {

}
//MARK: Presenter -
protocol BookPresenterProtocol: class {
    var books : [BookEntity]? { get }
    func getListBook()
}

//MARK: View -
protocol BookViewProtocol: class {
    func didGetListBook()
    var presenter: BookPresenterProtocol?  { get set }
}
