//
//  BookPresenter.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/19/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by NguyenNgocChau@VFA
//

import UIKit

class BookPresenter: BookPresenterProtocol {

    weak private var view: BookViewProtocol?
    private let router: BookWireframeProtocol
    
    var books: [BookEntity]?
    
    init(interface: BookViewProtocol, router: BookWireframeProtocol) {
        self.view = interface
        self.router = router
    }

    func getListBook() {
        let session = URLSession.shared
        let url = URL(string: "https://jsonplaceholder.typicode.com/todos")!
        session.dataTask(with: url) { (data, response, error) in
            if let books = try? JSONDecoder().decode([BookEntity].self, from: data!) {
                self.books = books
                self.view?.didGetListBook()
            }
        }.resume()
    }
}
