//
//  BookRouter.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/19/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by NguyenNgocChau@VFA
//

import UIKit

class BookRouter: BookWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = BookViewController(nibName: nil, bundle: nil)
        let router = BookRouter()
        let presenter = BookPresenter(interface: view, router: router)
        
        view.presenter = presenter
        router.viewController = view
        return view
    }
}
