//
//  BookPresenter.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/19/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by NguyenNgocChau@VFA
//

import UIKit

class BookPresenter: BookPresenterProtocol {

    weak private var view: BookViewProtocol?
    private let router: BookWireframeProtocol
    
    var movies: [MovieTopRateEntity]?
    
    init(interface: BookViewProtocol, router: BookWireframeProtocol) {
        self.view = interface
        self.router = router
    }

    func getListMovie() {
        Provider.shared.movieService.getTopRated(page: 1, successed: { [weak self] (listMovie) in
            guard let self = self else {return}
            self.movies = listMovie
            self.view?.didGetListMovie()
        }) { (error) in
            
        }
    }
}
