//
//  ForgotPasswordViewController.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/17/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ForgotPasswordViewController: UIViewController, ForgotPasswordViewProtocol {

	var presenter: ForgotPasswordPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
