//
//  ForgotPasswordRouter.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/17/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ForgotPasswordRouter: ForgotPasswordWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ForgotPasswordViewController(nibName: nil, bundle: nil)
        let router = ForgotPasswordRouter()
        let presenter = ForgotPasswordPresenter(interface: view, router: router)
        
        view.presenter = presenter
        router.viewController = view
        
        return view
    }
}
