# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestMVP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestMVP

  target 'TestMVPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestMVPUITests' do
    # Pods for testing
  end
end
