//
//  CirclePresenter.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/18/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by NguyenNgocChau@VFA
//

import UIKit

class CirclePresenter: CirclePresenterProtocol {

    weak private var view: CircleViewProtocol?
    private let router: CircleWireframeProtocol

    init(interface: CircleViewProtocol, router: CircleWireframeProtocol) {
        self.view = interface
        self.router = router
    }

}
