//
//  LoginRouter.swift
//  TestMVP
//
//  Created VFA-ChauNN on 12/19/19.
//  Copyright © 2019 VFA-ChauNN. All rights reserved.
//
//  Template generated by NguyenNgocChau@VFA
//

import UIKit

class LoginRouter: LoginWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LoginViewController(nibName: nil, bundle: nil)
        let router = LoginRouter()
        let presenter = LoginPresenter(interface: view, router: router)
        
        view.presenter = presenter
        router.viewController = view
        return view
    }
    
    func gotoBook() {
        let vc = BookRouter.createModule()
        self.viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
